SELECT 
	DISTINCT(s."SHOPNUMBER")
	, s."DATE"
	, sh."CITY" 
    , sh."ADDRESS" 
    , COUNT("QTY") OVER (PARTITION by s."SHOPNUMBER") AS SUM_QTY
    , SUM("QTY") OVER (PARTITION by s."SHOPNUMBER") AS SUM_QTY_PRICE 
FROM sales s 
LEFT JOIN shops sh ON sh."SHOPNUMBER" = s."SHOPNUMBER"
WHERE s."DATE" = '1/2/2016' 
ORDER BY s."SHOPNUMBER" 
